name: A workflow for myWeApp Application
on: push
jobs:
  build-job:
    name: myWeApp action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      name: Check out code
    - name: Check out code
      run: echo Hello World
    - name: Print index.html
      run: cat index.html
      
